### ISSUE TITLE
FPP mode needs improvement.

### ISSUE THREAD

**Issue by muzammil168** [oivio/Advanced-Camera-Manager#2]
First of all im very Thankful for what you are making, and i see that you implemented limiters in the camera thats good but the only issue now is both FPP AND TPP cameras are sharing same variables, If im setting limit for FPP to rotate on yaw axis from -90 to 90, the same change happens for TPP, because right now in FPP we can see our own body when we rotate 180 on yaw. You see here's the problem now we want complete 360 rotation for TPP but not for FPP, FPP should have a different variable to set its limit. 
Even adding a new variable will not solve the problem because if we set the rotation of FPP on yaw axis to be -90 to 90, we would not be able to turn our player, ive tried it.
I know it will be a big task but my proposed solution is in FPP the character should automatically rotate to where our camera is looking, I hope you get the issue.
Thanks again sir.
![Screenshot (1)](https://user-images.githubusercontent.com/82723658/126024759-59d2c606-99ba-41bc-b8aa-50b31e239351.png)

**Comment by oivio** [comment]
You should not add -90 to 90 but -89.9 to 89.9 and it will work. 
For others without problems, you can create separate limiters for FPS ant TPS just open "GetRotationLimiters" function and add them there:

![sol](https://user-images.githubusercontent.com/38628851/126035839-8a3a5b11-c576-4644-9a55-53a91c52a87e.jpg)

**Comment by oivio** [comment]
Latest Version has been improved with separate settings fr each view mode and "GetRotationLimiters"
